theme: jekyll-theme-cayman

title: Open-Insurance
description: Vendor neutral umbrella for all activities of open collaboration within the insurtech scene

github:
  is_project_page: true
  repository_url: https://github.com/open-insurance
